### ISSUE TITLE
Allow centered image for customization aka allow logo over QR code

### ISSUE THREAD

**Issue by peterpeterparker** [fluster/deckdeckgo-qrcode#2]
It would be cool, as suggested by Fernando on twitter, to have the ability to add an image/logo over the QR code

I think that should be possible, as the Level High (h) is used meaning inside the QR code the code is repeated multiple times so it's possible to hide a part aka to add an image over it, so basically it just need a slot

https://twitter.com/fm3ndoza/status/1079131832904572928?s=19

**Comment by fmendoza** [comment]
I'm not familiar with QR generation but if you're right it shouldn't be so hard to integrate this feature. Would be happy to help if you need anything.

**Comment by peterpeterparker** [comment]
@fmendoza I have implemented it and it seems that I was correct, it's possible to display a logo over a QR code by simply using a slot as the QR code encoded with the high correction level will repeat the content multiple time in the content

Would you like to have a look prior its release or should I just release the new version straight to npm?

If you want to have a try, the feature is in a branch called "logo" respectively:

    git clone https://github.com/fluster/deckdeckgo-qrcode -b logo
    cd deckdeckgo-qrcode
    npm install
    npm run start
 
cheers from my holiday ;)

**Comment by fmendoza** [comment]
sweet! it works great man! It's a nice use case for slots :-)

<img width="556" alt="captura de pantalla 2018-12-31 a la s 12 30 31" src="https://user-images.githubusercontent.com/1320696/50565804-42951500-0cf8-11e9-885a-0cce4f99a278.png">

Cheers!

**Comment by fmendoza** [comment]
Question. Is it possible to style the colors if the type is set to img?

**Comment by peterpeterparker** [comment]
@fmendoza sweet thx for the feedback, I'll release the new version later, cool to hear it work out

About colours if type is set to img, I tried quickly but didn't found. Maybe there is a solution but that would be inside of the QR generator and I didn't found (in the meantime I added a notice in the readme about that)

**Comment by peterpeterparker** [comment]
@fmendoza it should be possible to modify the colors when the type img is use, I'll track that in https://github.com/fluster/deckdeckgo-qrcode/issues/3
